### ISSUE TITLE
the latest gpt4 model dont support function calling with stream

### ISSUE THREAD

**Issue by melove93** [yaokui2018/chatgpt_example#1]
gpt-4-0125-preview and gpt-4-1106-preview model cant use this code
There seems to be a problem with the function calls output by these two models, as follows：
None[ChoiceDeltaToolCall(index=0, id='call_0BFsrWcQCDoEWnVOArx9DkPr', function=ChoiceDeltaToolCallFunction(arguments='{"city": "杭州"}{"user_id": 1002}', name='get_weather'), type='function')]

gpt-4 model's function calls are correct,as follows:
tool_calls: ChoiceDeltaToolCall(index=0, id='call_jaXTl40Gl8f2QxEwi3VVbo3h', function=ChoiceDeltaToolCallFunction(arguments='{\n  "city": "杭州"\n}', name='get_weather'), type='function')
tool_calls: ChoiceDeltaToolCall(index=0, id='call_aotfIjYZN4kK0JF6MQW8JLXD', function=ChoiceDeltaToolCallFunction(arguments='{\n  "user_id": 1002\n}', name='get_user_name'), type='function')
杭州今天的天气是晴天，气温在20℃左右。ID 1002的用户名是李四。

**Comment by yaokui2018** [comment]
你好，感谢反馈，该问题已修复，详见：[commit/e9cdd485ad6e5e75f87fce131db877ec9b2cb1a6](https://github.com/yaokui2018/chatgpt_example/commit/e9cdd485ad6e5e75f87fce131db877ec9b2cb1a6)
